// 주문 상태 필터 enum
export enum OrderStatusFilter {
    ALL = 'ALL',
    PAID = 'PAID',
    PURCHASE_CONFIRMED = 'PURCHASE_CONFIRMED',
    CANCEL_COMPLETED = 'CANCEL_COMPLETED',
    CANCEL_REJECTED = 'CANCEL_REJECTED',
    RETURN_REJECTED = 'RETURN_REJECTED',
    RETURN_COMPLETED = 'RETURN_COMPLETED',
    RETURN_RETURNED = 'RETURN_RETURNED',
    EXCHANGE_REJECTED = 'EXCHANGE_REJECTED',
    EXCHANGE_COMPLETED = 'EXCHANGE_COMPLETED',
    EXCHANGE_RETURNED = 'EXCHANGE_RETURNED',
}

// 검색 타입 enum
export enum SearchType {
    ORDER_NUMBER = 'ORDER_NUMBER',
    RECEIVER_NAME = 'RECEIVER_NAME',
    BUYER_NAME = 'BUYER_NAME',
    PRODUCT_NAME = 'PRODUCT_NAME',
    TRACKING_NUMBER = 'TRACKING_NUMBER',
}
